name: 🐞 Bug report
description: Create a report to help me improve
title: "[BUG]: "
labels: ["bug"]
assignees: romw314
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Device type
      options:
        - Desktop
        - Smartphone
        - Tablet
    validations:
      required: true
  - type: input
    attributes:
      label: Device
      placeholder: e.g. iPhone6
    validations:
      required: false
  - type: input
    attributes:
      label: OS
      placeholder: e.g. iOS
    validations:
      required: true
  - type: input
    attributes:
      label: Browser
      placeholder: e.g. Chrome, Safari
    validations:
      required: true
  - type: input
    attributes:
      label: Browser version
      placeholder: e.g. 22
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
